apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    account: {{ .Values.backend.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    service: {{ .Values.backend.name }}
spec:
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.targetPort }}
      name: http
  selector:
    app: {{ .Values.app }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    version: {{ .Values.version }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        version: {{ .Values.version }}
    spec:
      serviceAccountName: {{ .Values.backend.name }}
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.targetPort }}
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: uri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: redis-password
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.secretName }}
                  key: rabbitmq-password
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: config-prod-volume
              mountPath: /app/config/config.production.yaml
              subPath: config.production.yaml
              readOnly: true
      volumes:
        - name: config-volume
          secret:
            secretName: config
        - name: config-prod-volume
          secret:
            secretName: config-prod
