
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    service: {{ .Values.frontend.name }}
spec:
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
      name: http
  selector:
    app: {{ .Values.app }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    version: {{ .Values.version }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        version: {{ .Values.version }}
    spec:
      serviceAccountName: {{ .Values.frontend.name }}
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.targetPort }}