{{- if and .Values.postgresql.enabled .Values.postgresql.cloudNativePg.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.postgresql.namespace }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgresql.clusterName }}
  namespace: {{ .Values.postgresql.namespace }}
spec:
  instances: {{ .Values.postgresql.instances }}
  bootstrap:
    initdb:
      database: {{ .Values.postgresql.database }}
      owner: {{ .Values.postgresql.owner }}
  storage:
    size: {{ .Values.postgresql.storage.size }}
{{- end }}