apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.route.gateway.name }}
      namespace: {{ .Values.route.gateway.namespace }}
  hostnames:
    - {{ .Values.route.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/
      backendRefs:
        - name: {{ .Values.backend.name }}
          port: {{ .Values.backend.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.frontend.name }}
          port: {{ .Values.frontend.port }}