apiVersion: v1
kind: Namespace
metadata:
  name: jueju-db
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: jueju-db
  namespace: jueju-db
spec:
  instances: 3
  bootstrap:
    initdb:
      database: jueju
      owner: jueju

  storage:
    size: 1Gi
---
# Service entry for istio
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: jueju-db-rw-entry
  namespace: jueju
spec:
  hosts:
    - jueju-db-rw.jueju-db.svc.cluster.local
  ports:
    - number: 5432
      name: postgres
      protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: jueju-db-rw
  namespace: jueju
spec:
  host: jueju-db-rw.jueju-db.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
